--CREATE A TABLE NAMED STUDENT
CREATE TABLE STUDENT
(
 SID NUMBER(4),
 NAME VARCHAR2(15),
 AGE NUMBER(2)
 );
 
 --CREATE TABLE NAMED EMPLOYEE
  CREATE TABLE EMPLOYEE
  (
   EMPI_ID NUMBER(4),
   EMP_NAME VARCHAR2(20),
   SALARY NUMBER(8,2)
   );
   
   --CREATE TABLE NAMED DEPARTMENT
     CREATE TABLE DEPARTMENT
	 (
	  DEPTNO NUMBER(2),
	  DNAME VARCHAR2(15),
	  LOCATION CHAR(3)
	  );
	   
	 --CREATE TABLE NAMED PRODCUT
	  CREATE TABLE PRODUCT
	   (
	    PRODUC_ID NUMBER(10),
		 PRODUCT_NAME VARCHAR2(20),
		 PRICE FLOAT;
		  STOCK FLOAT;
		  );
		  
		  --CREATE TABLE NAMED CUSTOMER
		   CREATE TABLE CUSTOMER
		    COUSTMER_ID NUMBER(4),
			CNAME VARCHAR2(20),
			PHONE INT;
			 EMAIL VARCHAR2(30),
			 city CHAR(3)
			 );
			 
			  --CREATE TABLE NAMED EMPLOYEE(USING CONSTRAINTS)
			   CREATE TABLE EMPLOYEE
			   (
			    EMP_ID NUMBER(4) CONSTRAINT EMP_C_ID PRIMARY KEY,
				ENAME VARCHAR2(10) CONSTRAINT EMP_N_NAME NOT NULL,
				SALARY FLOAT CONSTRAINT EMP_S_AMT CHECK(SAL>0)
				);
				 
				 --CREATE TABLE NAMED STUDENT(USING CONSTRAINT)
				  CREATE TABLE STUDENT
				  (
				   ROLL_NO NUMBER(2) CONSTRAINT STUDENT_ROLL PRIMARY KEY,
				   NAME VARCHAR2(15) CONSTRAINT STUDENT_N NOT NULL,
				   EMAIL VARCHAR2(30) CONSTRAINT STUDENT_MAIL UNIQUE,
				   AGE NUMBER(2)  CONSTRAINT STUDENT_AGES CHECK(AGE>=18)
				   ); 
				   
				     --CREATE NAME BANK_ACCOUNT (USING CONSTRAINTS)
					  CREATE TABLE BANK_ACCOUNT)
					  (
					   ACCOUNT_NO NUMBER(10) CONSTRAINT ACC_PK PRIMARY KEY,
					   HOLDER_NAME VARCHAR2(40) CONSTRAINT ACC_NAME_NN NOT NULL,
					   ACCOUNT_TYPE VARCHAR2(15),
					   BALANCE NUMBER(10,2) CONSTRAINT ACC_BAL_CK CHECK(BALANCE>=1000),
					   EMAIL VARCHAR2(30) CONSTRAINT ACC_MAIL_UK UNIQUE
					   );